import { useEffect, type ReactNode } from 'react'
import { Link } from 'react-router-dom'
import { Activity, ArrowUpRight, RefreshCw, Settings2, Table2, UsersRound, LayoutGrid } from 'lucide-react'
import { Badge, Button, Card } from '../components/ui'
import { useAppStore } from '../store/appStore'
import { metricLabels } from '../types'

export default function DashboardPage() {
  const { rankings, snapshot, loading, error, view, setView, refresh } = useAppStore()
  useEffect(() => { void (async () => { await useAppStore.getState().hydrate(); if (!useAppStore.getState().snapshot) await useAppStore.getState().refresh() })() }, [])
  const totals = rankings.reduce((acc, c) => ({ commits: acc.commits + c.commits, prs: acc.prs + c.prs, reviews: acc.reviews + c.reviews }), { commits: 0, prs: 0, reviews: 0 })
  return <main className="mx-auto max-w-6xl space-y-8 px-6 py-8">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end">
      <div><div className="mb-2 flex items-center gap-2 text-sm text-primary"><Activity size={16} /> CONTRIBUTOR RANK</div><h1 className="text-3xl font-semibold tracking-tight">贡献者排行榜</h1><p className="mt-2 text-muted-foreground">用透明、可配置的指标看见每一份开源贡献。</p></div>
      <div className="flex gap-2"><Button variant="outline" onClick={() => void refresh()} disabled={loading}><RefreshCw size={16} className={loading ? 'mr-2 animate-spin' : 'mr-2'} />刷新数据</Button><Link to="/settings"><Button variant="outline"><Settings2 size={16} className="mr-2" />设置</Button></Link></div>
    </div>
    {error && <Card className="border-destructive/50 bg-destructive/10 p-4 text-sm text-destructive">{error}</Card>}
    <div className="grid gap-4 md:grid-cols-3"><Stat label="贡献者" value={rankings.length} icon={<UsersRound size={18} />} /><Stat label="Commits" value={totals.commits.toLocaleString()} /><Stat label="PR / Review" value={`${totals.prs} / ${totals.reviews}`} /></div>
    <Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-border p-5"><div><h2 className="font-semibold">{snapshot?.repository || '正在加载仓库…'}</h2><p className="text-xs text-muted-foreground">{snapshot ? `更新于 ${new Date(snapshot.fetchedAt).toLocaleString()}` : '首次分析可能需要几秒钟'}</p></div><div className="flex rounded-md border border-border p-1"><Button variant={view === 'table' ? 'default' : 'ghost'} className="h-8 px-2" onClick={() => setView('table')} aria-label="表格视图"><Table2 size={16} /></Button><Button variant={view === 'cards' ? 'default' : 'ghost'} className="h-8 px-2" onClick={() => setView('cards')} aria-label="卡片视图"><LayoutGrid size={16} /></Button></div></div>
      {loading && rankings.length === 0 ? <div className="p-12 text-center text-muted-foreground">正在获取仓库数据…</div> : rankings.length === 0 ? <div className="p-12 text-center text-muted-foreground">暂无数据，请在设置中配置仓库。</div> : view === 'table' ? <RankingTable rankings={rankings} /> : <RankingCards rankings={rankings} />}
    </Card>
  </main>
}

function Stat({ label, value, icon }: { label: string; value: string | number; icon?: ReactNode }) { return <Card className="p-4"><div className="flex items-center gap-2 text-sm text-muted-foreground">{icon}<span>{label}</span></div><p className="mt-2 text-2xl font-semibold">{value}</p></Card> }

function RankingTable({ rankings }: { rankings: ReturnType<typeof useAppStore.getState>['rankings'] }) { return <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/40 text-left text-xs uppercase text-muted-foreground"><tr><th className="px-5 py-3">排名</th><th className="px-5 py-3">贡献者</th><th className="px-5 py-3">综合分</th><th className="px-5 py-3">Commits</th><th className="px-5 py-3">LoC</th><th className="px-5 py-3">PR</th><th className="px-5 py-3">Review</th><th /></tr></thead><tbody>{rankings.map(c => <tr key={c.login} className="border-t border-border"><td className="px-5 py-4 font-semibold">{c.rank <= 3 ? ['🥇', '🥈', '🥉'][c.rank - 1] : `#${c.rank}`}</td><td className="px-5 py-4"><Link to={`/contributors/${encodeURIComponent(c.login)}`} className="flex items-center gap-3 hover:text-primary"><Avatar name={c.name} src={c.avatarUrl} /><span><span className="block font-medium">{c.name}</span><span className="text-xs text-muted-foreground">@{c.login}</span></span></Link></td><td className="px-5 py-4 font-semibold text-primary">{c.score.toFixed(2)}</td><td className="px-5 py-4">{c.commits}</td><td className="px-5 py-4">{(c.additions + c.deletions).toLocaleString()}</td><td className="px-5 py-4">{c.mergedPrs}/{c.prs}</td><td className="px-5 py-4">{c.reviews}</td><td className="px-5 py-4"><Link to={`/contributors/${encodeURIComponent(c.login)}`}><ArrowUpRight size={17} className="text-muted-foreground" /></Link></td></tr>)}</tbody></table></div> }
function RankingCards({ rankings }: { rankings: ReturnType<typeof useAppStore.getState>['rankings'] }) { return <div className="grid gap-4 p-5 md:grid-cols-2 lg:grid-cols-3">{rankings.map(c => <Link key={c.login} to={`/contributors/${encodeURIComponent(c.login)}`}><Card className="p-4 transition hover:-translate-y-0.5 hover:border-primary/60"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><Avatar name={c.name} src={c.avatarUrl} /><div><p className="font-medium">{c.name}</p><p className="text-xs text-muted-foreground">@{c.login}</p></div></div><Badge>#{c.rank}</Badge></div><p className="mt-5 text-3xl font-semibold text-primary">{c.score.toFixed(2)}<span className="ml-1 text-xs font-normal text-muted-foreground">score</span></p><div className="mt-4 grid grid-cols-3 gap-2 text-xs text-muted-foreground"><span>Commit<br /><b className="text-foreground">{c.commits}</b></span><span>PR<br /><b className="text-foreground">{c.mergedPrs}/{c.prs}</b></span><span>Review<br /><b className="text-foreground">{c.reviews}</b></span></div></Card></Link>)}</div> }
function Avatar({ name, src }: { name: string; src?: string }) { return src ? <img src={src} alt="" className="h-9 w-9 rounded-full" /> : <div className="flex h-9 w-9 items-center justify-center rounded-full bg-primary/15 text-sm font-semibold text-primary">{name.split(' ').map(x => x[0]).join('').slice(0, 2)}</div> }
