import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowLeft, Check, Database, KeyRound, Save } from 'lucide-react'
import { open } from '@tauri-apps/plugin-dialog'
import { Badge, Button, Card, Input, Label, Slider } from '../components/ui'
import { metricLabels, type MetricKey } from '../types'
import { useAppStore } from '../store/appStore'

const metricKeys = Object.keys(metricLabels) as MetricKey[]
export default function SettingsPage() {
  const { settings, setSettings, setWeight, persistSettings, recalculate } = useAppStore(); const [saved, setSaved] = useState(false)
  useEffect(() => { void useAppStore.getState().hydrate() }, [])
  useEffect(() => { if (useAppStore.getState().snapshot) void recalculate() }, [settings.weights, recalculate])
  async function onSave() { await persistSettings(); setSaved(true); window.setTimeout(() => setSaved(false), 1800); if (useAppStore.getState().snapshot) await recalculate() }
  async function pickFolder() { try { const selected = await open({ directory: true, multiple: false, title: '选择本地 Git 仓库' }); if (typeof selected === 'string') setSettings({ repository: selected }) } catch { /* Browser preview does not expose native dialog. */ } }
  return <main className="mx-auto max-w-3xl space-y-6 px-6 py-8"><Link to="/" className="inline-flex items-center text-sm text-muted-foreground hover:text-foreground"><ArrowLeft size={16} className="mr-2" />返回排行榜</Link><div><h1 className="text-3xl font-semibold">设置</h1><p className="mt-2 text-muted-foreground">配置数据源与排名算法，保存后可随时重新分析。</p></div><Card className="space-y-5 p-6"><div className="flex items-center gap-2 font-semibold"><Database size={18} className="text-primary" />数据源</div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>平台</Label><select value={settings.provider} onChange={e => setSettings({ provider: e.target.value as typeof settings.provider })} className="h-10 w-full rounded-md border border-border bg-background px-3 text-sm"><option value="github">GitHub</option><option value="gitlab">GitLab</option><option value="local">本地 Git 仓库</option></select></div><div className="space-y-2"><Label>仓库地址 / 路径</Label><div className="flex gap-2"><Input value={settings.repository} onChange={e => setSettings({ repository: e.target.value })} placeholder={settings.provider === 'local' ? '/Users/me/project' : 'owner/repository'} />{settings.provider === 'local' && <Button type="button" variant="outline" onClick={() => void pickFolder()}>选择</Button>}</div></div></div><div className="space-y-2"><Label className="flex items-center gap-2"><KeyRound size={15} />Personal Access Token <span className="font-normal text-muted-foreground">（仅保存在本机）</span></Label><Input type="password" value={settings.token} onChange={e => setSettings({ token: e.target.value })} placeholder="ghp_… / glpat-…" /></div></Card><Card className="space-y-6 p-6"><div><div className="flex items-center gap-2 font-semibold">排名权重 <Badge>实时重算</Badge></div><p className="mt-1 text-sm text-muted-foreground">权重范围 0–2，0 表示忽略该指标。</p></div>{metricKeys.map(key => <div key={key} className="grid items-center gap-3 sm:grid-cols-[150px_1fr_70px]"><Label>{metricLabels[key]}</Label><Slider value={settings.weights[key]} onChange={value => setWeight(key, value)} /><Input type="number" min="0" max="2" step="0.1" value={settings.weights[key]} onChange={e => setWeight(key, Math.min(2, Math.max(0, Number(e.target.value))))} /></div>)}</Card><div className="flex justify-end"><Button onClick={() => void onSave()}>{saved ? <><Check size={16} className="mr-2" />已保存</> : <><Save size={16} className="mr-2" />保存设置</>}</Button></div></main>
}
